//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotServer.Types {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotServer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;rtde_config&gt;
        ///  &lt;receive key=&quot;out&quot;&gt;
        ///    &lt;field name=&quot;timestamp&quot; type=&quot;DOUBLE&quot;/&gt;
        ///    &lt;!-- This tag may not be removed!!! --&gt;
        ///    &lt;field name=&quot;actual_digital_output_bits&quot; type=&quot;UINT64&quot;/&gt;
        ///
        ///    &lt;field name=&quot;actual_q&quot; type=&quot;VECTOR6D&quot;/&gt;
        ///    &lt;field name=&quot;actual_qd&quot; type=&quot;VECTOR6D&quot;/&gt;
        ///    &lt;field name=&quot;actual_TCP_pose&quot; type=&quot;VECTOR6D&quot;/&gt;
        ///    &lt;field name=&quot;actual_TCP_force&quot; type=&quot;VECTOR6D&quot;/&gt;
        ///    &lt;field name=&quot;actual_digital_input_bits&quot; type=&quot;UINT64&quot;/&gt;
        ///    &lt;field name=&quot;robot_mode&quot; type=&quot;INT32&quot;/&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rtde_configuration {
            get {
                return ResourceManager.GetString("rtde_configuration", resourceCulture);
            }
        }
    }
}
